2024-05-17 22:32:16,860 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-17 22:32:16,861 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Configure stats pid to 3757
2024-05-17 22:32:16,861 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-17 22:32:16,861 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/MiniGPT/wandb/settings
2024-05-17 22:32:16,861 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-17 22:32:16,862 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-17 22:32:16,862 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-17 22:32:16,862 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-17 22:32:16,862 WARNING MainThread:3757 [wandb_setup.py:_flush():76] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-31-0cabb18e0257>", line 32, in <cell line: 31>
    wandb.init(project="dl2_proj3")
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1163, in init
    wi.setup(kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 300, in setup
    wandb_login._login(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 334, in _login
    wlogin.prompt_api_key()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 256, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 236, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/apikey.py", line 97, in prompt_api_key
    key = wandb.jupyter.attempt_colab_login(app_url)
  File "/usr/local/lib/python3.10/dist-packages/wandb/jupyter.py", line 323, in attempt_colab_login
    return output.eval_js("_wandbApiKey")
  File "/usr/local/lib/python3.10/dist-packages/google/colab/output/_js.py", line 40, in eval_js
    return _message.read_reply_from_input(request_id, timeout_sec)
  File "/usr/local/lib/python3.10/dist-packages/google/colab/_message.py", line 96, in read_reply_from_input
    time.sleep(0.025)
KeyboardInterrupt
2024-05-17 22:32:16,862 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-17 22:32:16,862 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-17 22:32:16,863 INFO    MainThread:3757 [wandb_init.py:_log_setup():520] Logging user logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240517_223216-ask1455z/logs/debug.log
2024-05-17 22:32:16,863 INFO    MainThread:3757 [wandb_init.py:_log_setup():521] Logging internal logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240517_223216-ask1455z/logs/debug-internal.log
2024-05-17 22:32:16,863 INFO    MainThread:3757 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9fe238f940>
2024-05-17 22:32:16,864 INFO    MainThread:3757 [wandb_init.py:init():560] calling init triggers
2024-05-17 22:32:16,864 INFO    MainThread:3757 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-17 22:32:16,864 INFO    MainThread:3757 [wandb_init.py:init():585] re-initializing run, found existing run on stack: p5i8f0lp
2024-05-17 22:32:16,866 INFO    MainThread:3757 [wandb_run.py:_finish():2103] finishing run zxzucla/dl2_proj3/p5i8f0lp
2024-05-17 22:32:16,866 INFO    MainThread:3757 [wandb_run.py:_atexit_cleanup():2343] got exitcode: 0
2024-05-17 22:32:16,867 INFO    MainThread:3757 [wandb_run.py:_restore():2326] restore
2024-05-17 22:32:16,867 INFO    MainThread:3757 [wandb_run.py:_restore():2332] restore done
2024-05-17 22:32:21,168 INFO    MainThread:3757 [wandb_run.py:_footer_history_summary_info():3994] rendering history
2024-05-17 22:32:21,169 INFO    MainThread:3757 [wandb_run.py:_footer_history_summary_info():4026] rendering summary
2024-05-17 22:32:21,179 INFO    MainThread:3757 [wandb_run.py:_footer_sync_info():3953] logging synced files
2024-05-17 22:32:21,184 INFO    MainThread:3757 [wandb_init.py:init():610] starting backend
2024-05-17 22:32:21,184 INFO    MainThread:3757 [wandb_init.py:init():614] setting up manager
2024-05-17 22:32:21,188 INFO    MainThread:3757 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-17 22:32:21,188 INFO    MainThread:3757 [wandb_init.py:init():622] backend started and connected
2024-05-17 22:32:21,201 INFO    MainThread:3757 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-17 22:32:21,504 INFO    MainThread:3757 [wandb_init.py:init():711] updated telemetry
2024-05-17 22:32:21,553 INFO    MainThread:3757 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-17 22:32:22,358 INFO    MainThread:3757 [wandb_run.py:_on_init():2396] communicating current version
2024-05-17 22:32:22,492 INFO    MainThread:3757 [wandb_run.py:_on_init():2405] got version response 
2024-05-17 22:32:22,492 INFO    MainThread:3757 [wandb_init.py:init():795] starting run threads in backend
2024-05-17 22:32:22,929 INFO    MainThread:3757 [wandb_run.py:_console_start():2374] atexit reg
2024-05-17 22:32:22,929 INFO    MainThread:3757 [wandb_run.py:_redirect():2229] redirect: wrap_raw
2024-05-17 22:32:22,929 INFO    MainThread:3757 [wandb_run.py:_redirect():2294] Wrapping output streams.
2024-05-17 22:32:22,930 INFO    MainThread:3757 [wandb_run.py:_redirect():2319] Redirects installed.
2024-05-17 22:32:22,931 INFO    MainThread:3757 [wandb_init.py:init():838] run started, returning control to user process
2024-05-17 22:35:20,853 INFO    MainThread:3757 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-05-17 22:35:20,854 INFO    MainThread:3757 [wandb_init.py:_pause_backend():431] pausing backend
2024-05-17 22:35:34,639 INFO    MainThread:3757 [wandb_init.py:_resume_backend():436] resuming backend
2024-05-17 22:35:34,755 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-17 22:35:34,756 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Configure stats pid to 3757
2024-05-17 22:35:34,756 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-17 22:35:34,756 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/MiniGPT/wandb/settings
2024-05-17 22:35:34,757 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-17 22:35:34,757 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-17 22:35:34,757 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-17 22:35:34,757 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-17 22:35:34,757 WARNING MainThread:3757 [wandb_setup.py:_flush():76] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-31-0cabb18e0257>", line 32, in <cell line: 31>
    wandb.init(project="dl2_proj3")
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1163, in init
    wi.setup(kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 300, in setup
    wandb_login._login(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 334, in _login
    wlogin.prompt_api_key()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 256, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 236, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/apikey.py", line 97, in prompt_api_key
    key = wandb.jupyter.attempt_colab_login(app_url)
  File "/usr/local/lib/python3.10/dist-packages/wandb/jupyter.py", line 323, in attempt_colab_login
    return output.eval_js("_wandbApiKey")
  File "/usr/local/lib/python3.10/dist-packages/google/colab/output/_js.py", line 40, in eval_js
    return _message.read_reply_from_input(request_id, timeout_sec)
  File "/usr/local/lib/python3.10/dist-packages/google/colab/_message.py", line 96, in read_reply_from_input
    time.sleep(0.025)
KeyboardInterrupt
2024-05-17 22:35:34,758 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-17 22:35:34,758 INFO    MainThread:3757 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-17 22:35:34,758 INFO    MainThread:3757 [wandb_init.py:_log_setup():520] Logging user logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240517_223534-43lz065v/logs/debug.log
2024-05-17 22:35:34,758 INFO    MainThread:3757 [wandb_init.py:_log_setup():521] Logging internal logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240517_223534-43lz065v/logs/debug-internal.log
2024-05-17 22:35:34,758 INFO    MainThread:3757 [wandb_init.py:init():560] calling init triggers
2024-05-17 22:35:34,759 INFO    MainThread:3757 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-17 22:35:34,759 INFO    MainThread:3757 [wandb_init.py:init():585] re-initializing run, found existing run on stack: ask1455z
2024-05-17 22:35:34,761 INFO    MainThread:3757 [wandb_run.py:_finish():2103] finishing run zxzucla/dl2_proj3/ask1455z
2024-05-17 22:35:34,761 INFO    MainThread:3757 [jupyter.py:save_history():445] not saving jupyter history
2024-05-17 22:35:34,761 INFO    MainThread:3757 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-05-17 22:35:34,762 INFO    MainThread:3757 [wandb_init.py:_jupyter_teardown():448] cleaning up jupyter logic
2024-05-17 22:35:34,762 INFO    MainThread:3757 [wandb_run.py:_atexit_cleanup():2343] got exitcode: 0
2024-05-17 22:35:34,763 INFO    MainThread:3757 [wandb_run.py:_restore():2326] restore
2024-05-17 22:35:34,763 INFO    MainThread:3757 [wandb_run.py:_restore():2332] restore done
2024-05-17 22:35:43,041 INFO    MainThread:3757 [wandb_run.py:_footer_history_summary_info():3994] rendering history
2024-05-17 22:35:43,042 INFO    MainThread:3757 [wandb_run.py:_footer_history_summary_info():4026] rendering summary
2024-05-17 22:35:43,054 INFO    MainThread:3757 [wandb_run.py:_footer_sync_info():3953] logging synced files
