2024-05-18 18:49:51,916 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-18 18:49:51,917 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Configure stats pid to 6249
2024-05-18 18:49:51,917 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-18 18:49:51,917 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/MiniGPT/wandb/settings
2024-05-18 18:49:51,918 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-18 18:49:51,918 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 18:49:51,918 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-18 18:49:51,918 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-18 18:49:51,918 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-18 18:49:51,918 INFO    MainThread:6249 [wandb_init.py:_log_setup():520] Logging user logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240518_184951-j4qxfy0r/logs/debug.log
2024-05-18 18:49:51,919 INFO    MainThread:6249 [wandb_init.py:_log_setup():521] Logging internal logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240518_184951-j4qxfy0r/logs/debug-internal.log
2024-05-18 18:49:51,919 INFO    MainThread:6249 [wandb_init.py:init():560] calling init triggers
2024-05-18 18:49:51,919 INFO    MainThread:6249 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-18 18:49:51,919 INFO    MainThread:6249 [wandb_init.py:init():585] re-initializing run, found existing run on stack: nqberhcq
2024-05-18 18:49:51,921 INFO    MainThread:6249 [wandb_run.py:_finish():2103] finishing run zxzucla/dl2_proj3_minigpt/nqberhcq
2024-05-18 18:49:51,921 INFO    MainThread:6249 [jupyter.py:save_history():445] not saving jupyter history
2024-05-18 18:49:51,922 INFO    MainThread:6249 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-05-18 18:49:51,922 INFO    MainThread:6249 [wandb_init.py:_jupyter_teardown():448] cleaning up jupyter logic
2024-05-18 18:49:51,922 INFO    MainThread:6249 [wandb_run.py:_atexit_cleanup():2343] got exitcode: 0
2024-05-18 18:49:51,922 INFO    MainThread:6249 [wandb_run.py:_restore():2326] restore
2024-05-18 18:49:51,923 INFO    MainThread:6249 [wandb_run.py:_restore():2332] restore done
2024-05-18 18:50:11,534 INFO    MainThread:6249 [wandb_init.py:init():610] starting backend
2024-05-18 18:50:11,534 INFO    MainThread:6249 [wandb_init.py:init():614] setting up manager
2024-05-18 18:50:11,538 INFO    MainThread:6249 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-18 18:50:11,539 INFO    MainThread:6249 [wandb_init.py:init():622] backend started and connected
2024-05-18 18:50:11,553 INFO    MainThread:6249 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-18 18:50:16,579 INFO    MainThread:6249 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-18 18:50:16,579 INFO    MainThread:6249 [wandb_init.py:init():711] updated telemetry
2024-05-18 18:50:16,606 INFO    MainThread:6249 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-18 18:50:33,264 WARNING MainThread:6249 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 747, in init
    result = run_init_handle.wait(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-05-18 18:51:06,735 INFO    MainThread:6249 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-18 18:51:06,782 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-18 18:51:06,784 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Configure stats pid to 6249
2024-05-18 18:51:06,784 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-18 18:51:06,784 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/MiniGPT/wandb/settings
2024-05-18 18:51:06,784 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-18 18:51:06,785 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 18:51:06,785 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-18 18:51:06,785 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-18 18:51:06,785 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-18 18:51:06,785 INFO    MainThread:6249 [wandb_init.py:_log_setup():520] Logging user logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240518_185106-3v2x5xpa/logs/debug.log
2024-05-18 18:51:06,786 INFO    MainThread:6249 [wandb_init.py:_log_setup():521] Logging internal logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240518_185106-3v2x5xpa/logs/debug-internal.log
2024-05-18 18:51:06,786 INFO    MainThread:6249 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x78b81c4400a0>
2024-05-18 18:51:06,786 INFO    MainThread:6249 [wandb_init.py:init():560] calling init triggers
2024-05-18 18:51:06,786 INFO    MainThread:6249 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-18 18:51:06,786 INFO    MainThread:6249 [wandb_init.py:init():610] starting backend
2024-05-18 18:51:06,787 INFO    MainThread:6249 [wandb_init.py:init():614] setting up manager
2024-05-18 18:51:06,790 INFO    MainThread:6249 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-18 18:51:06,790 INFO    MainThread:6249 [wandb_init.py:init():622] backend started and connected
2024-05-18 18:51:06,804 INFO    MainThread:6249 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-18 18:51:07,183 INFO    MainThread:6249 [wandb_init.py:init():711] updated telemetry
2024-05-18 18:51:07,215 INFO    MainThread:6249 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-18 18:52:37,278 ERROR   MainThread:6249 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-18 18:52:37,278 ERROR   MainThread:6249 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-18 18:53:21,005 INFO    MainThread:6249 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-18 18:53:21,066 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-18 18:53:21,067 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Configure stats pid to 6249
2024-05-18 18:53:21,067 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-18 18:53:21,067 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/MiniGPT/wandb/settings
2024-05-18 18:53:21,067 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-18 18:53:21,068 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 18:53:21,068 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-18 18:53:21,068 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-18 18:53:21,068 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-18 18:53:21,069 INFO    MainThread:6249 [wandb_init.py:_log_setup():520] Logging user logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240518_185321-2rzb5wqi/logs/debug.log
2024-05-18 18:53:21,069 INFO    MainThread:6249 [wandb_init.py:_log_setup():521] Logging internal logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240518_185321-2rzb5wqi/logs/debug-internal.log
2024-05-18 18:53:21,069 INFO    MainThread:6249 [wandb_init.py:init():560] calling init triggers
2024-05-18 18:53:21,069 INFO    MainThread:6249 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-18 18:53:21,070 INFO    MainThread:6249 [wandb_init.py:init():610] starting backend
2024-05-18 18:53:21,070 INFO    MainThread:6249 [wandb_init.py:init():614] setting up manager
2024-05-18 18:53:21,073 INFO    MainThread:6249 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-18 18:53:21,074 INFO    MainThread:6249 [wandb_init.py:init():622] backend started and connected
2024-05-18 18:53:21,087 INFO    MainThread:6249 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-18 18:53:21,517 INFO    MainThread:6249 [wandb_init.py:init():711] updated telemetry
2024-05-18 18:53:21,553 INFO    MainThread:6249 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-18 18:53:24,838 WARNING MainThread:6249 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 747, in init
    result = run_init_handle.wait(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-05-18 18:53:43,528 INFO    MainThread:6249 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-18 18:53:43,568 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-18 18:53:43,569 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Configure stats pid to 6249
2024-05-18 18:53:43,570 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-18 18:53:43,570 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/MiniGPT/wandb/settings
2024-05-18 18:53:43,571 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-18 18:53:43,571 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 18:53:43,572 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-18 18:53:43,572 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-18 18:53:43,572 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-18 18:53:43,573 INFO    MainThread:6249 [wandb_init.py:_log_setup():520] Logging user logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240518_185343-41ezbu7b/logs/debug.log
2024-05-18 18:53:43,574 INFO    MainThread:6249 [wandb_init.py:_log_setup():521] Logging internal logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240518_185343-41ezbu7b/logs/debug-internal.log
2024-05-18 18:53:43,574 INFO    MainThread:6249 [wandb_init.py:init():560] calling init triggers
2024-05-18 18:53:43,575 INFO    MainThread:6249 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-18 18:53:43,575 INFO    MainThread:6249 [wandb_init.py:init():610] starting backend
2024-05-18 18:53:43,576 INFO    MainThread:6249 [wandb_init.py:init():614] setting up manager
2024-05-18 18:53:43,581 INFO    MainThread:6249 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-18 18:53:43,582 INFO    MainThread:6249 [wandb_init.py:init():622] backend started and connected
2024-05-18 18:53:43,596 INFO    MainThread:6249 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-18 18:53:43,925 INFO    MainThread:6249 [wandb_init.py:init():711] updated telemetry
2024-05-18 18:53:43,976 INFO    MainThread:6249 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-18 18:53:47,222 WARNING MainThread:6249 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 747, in init
    result = run_init_handle.wait(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
