2024-05-17 22:53:32,413 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-17 22:53:32,414 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Configure stats pid to 3525
2024-05-17 22:53:32,415 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-17 22:53:32,416 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/MiniGPT/wandb/settings
2024-05-17 22:53:32,416 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-17 22:53:32,417 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-17 22:53:32,417 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-17 22:53:32,417 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-17 22:53:32,418 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-17 22:53:32,418 INFO    MainThread:3525 [wandb_init.py:_log_setup():520] Logging user logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240517_225332-0kjp1fac/logs/debug.log
2024-05-17 22:53:32,419 INFO    MainThread:3525 [wandb_init.py:_log_setup():521] Logging internal logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240517_225332-0kjp1fac/logs/debug-internal.log
2024-05-17 22:53:32,419 INFO    MainThread:3525 [wandb_init.py:init():560] calling init triggers
2024-05-17 22:53:32,419 INFO    MainThread:3525 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-17 22:53:32,420 INFO    MainThread:3525 [wandb_init.py:init():610] starting backend
2024-05-17 22:53:32,420 INFO    MainThread:3525 [wandb_init.py:init():614] setting up manager
2024-05-17 22:53:32,424 ERROR   MainThread:3525 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 615, in init
    manager._inform_init(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-05-17 22:56:45,445 INFO    MainThread:3525 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-17 22:56:45,496 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-17 22:56:45,498 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Configure stats pid to 3525
2024-05-17 22:56:45,499 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-17 22:56:45,500 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/MiniGPT/wandb/settings
2024-05-17 22:56:45,500 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-17 22:56:45,501 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-17 22:56:45,502 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-17 22:56:45,502 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-17 22:56:45,503 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-17 22:56:45,504 INFO    MainThread:3525 [wandb_init.py:_log_setup():520] Logging user logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240517_225645-yvue8hlo/logs/debug.log
2024-05-17 22:56:45,505 INFO    MainThread:3525 [wandb_init.py:_log_setup():521] Logging internal logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240517_225645-yvue8hlo/logs/debug-internal.log
2024-05-17 22:56:45,506 INFO    MainThread:3525 [wandb_init.py:init():560] calling init triggers
2024-05-17 22:56:45,506 INFO    MainThread:3525 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-17 22:56:45,507 INFO    MainThread:3525 [wandb_init.py:init():610] starting backend
2024-05-17 22:56:45,508 INFO    MainThread:3525 [wandb_init.py:init():614] setting up manager
2024-05-17 22:56:45,514 ERROR   MainThread:3525 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 615, in init
    manager._inform_init(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-05-17 22:56:58,812 INFO    MainThread:3525 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-17 22:56:58,871 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-17 22:56:58,873 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Configure stats pid to 3525
2024-05-17 22:56:58,873 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-17 22:56:58,874 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/MiniGPT/wandb/settings
2024-05-17 22:56:58,874 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-17 22:56:58,875 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-17 22:56:58,876 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-17 22:56:58,876 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-17 22:56:58,877 INFO    MainThread:3525 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-17 22:56:58,878 INFO    MainThread:3525 [wandb_init.py:_log_setup():520] Logging user logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240517_225658-274iw3nv/logs/debug.log
2024-05-17 22:56:58,878 INFO    MainThread:3525 [wandb_init.py:_log_setup():521] Logging internal logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240517_225658-274iw3nv/logs/debug-internal.log
2024-05-17 22:56:58,879 INFO    MainThread:3525 [wandb_init.py:init():560] calling init triggers
2024-05-17 22:56:58,881 INFO    MainThread:3525 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-17 22:56:58,882 INFO    MainThread:3525 [wandb_init.py:init():610] starting backend
2024-05-17 22:56:58,882 INFO    MainThread:3525 [wandb_init.py:init():614] setting up manager
2024-05-17 22:56:58,887 ERROR   MainThread:3525 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 615, in init
    manager._inform_init(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
